apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx-deploy
  namespace: k8s-user-1
spec:
  replicas: 2
  selector:
    matchLabels:
      run: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1 # 升級過程中最多可以比原先設定所多出的 pod 數量
      maxUnavailable: 1 # 最多可以有幾個 pod 處在無法服務的狀態
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: morningstar3718/k8s-hw-nginx-reverse-proxy:32e3953
        imagePullPolicy: IfNotPresent
        name: nginx-reverse-proxy
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 200m
        volumeMounts:
        - mountPath: /var/log/nginx/
          name: log-volume
      - image: tachingchen/fluentd:0.1
        name: fluentd
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /var/log/nginx/
          name: log-volume
      volumes:
      - name: log-volume
        emptyDir: {}

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
  namespace: k8s-user-1
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deploy
  targetCPUUtilizationPercentage: 50
