apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: k8s-user-1
  labels:
    run: nginx
spec:
  type: NodePort
  selector:
    run: nginx
  ports:
  - port: 80 # 服務之間互相訪問的 port
    protocol: TCP
    targetPort: 80 # 後端 pod 暴露的 port
  sessionAffinity: None