apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: k8s-user-1
  labels:
    run: web
spec:
  selector:
    run: web
  ports:
  - port: 5566 # 服務之間互相訪問的 port
    protocol: TCP
    targetPort: 12345 # 後端 pod 暴露的 port
