apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80 # 服務之間互相訪問的 port
    protocol: TCP
    targetPort: 80 # 後端 pod 暴露的 port
  sessionAffinity: None
