apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
  namespace: default
  labels:
    app: nginx
    backend: go
spec:
  containers:
  - image: nginx:latest
    name: nginx
    ports:
    - containerPort: 80 # container port
      protocol: TCP
    volumeMounts:
    - name: secret-account
      mountPath: /usr/share/nginx/html # nginx 預設目錄
      readOnly: true
  volumes:
  - name: secret-account
    secret:
      secretName: account
      items:
      - key: account
        path: index.html # 檔名為 nginx 預設連線的檔名，之後連線可以不指定檔名
