apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-3
  namespace: default
  labels:
    app: nginx
    env: reverse-proxy
spec:
  containers:
  - image: morningstar3718/k8s-hw-nginx-reverse-proxy:32e3953
    name: nginx-reverse-proxy
    ports:
      - containerPort: 80 # container port
        protocol: TCP
    resources:
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits:
        memory: "100Mi"
        cpu: "100m"
