apiVersion: v1
kind: Pod
metadata:
  name: web-server
  namespace: default
  labels:
    app: web-server
    backend: go
spec:
  containers:
  - image: morningstar3718/k8s-hw-web-server:cc11346
    name: k8s-hw-web-server
    ports:
    - containerPort: 5566 # container port
      protocol: TCP
